{% set name = "groq" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/groq-{{ version }}.tar.gz
  sha256: 2a201d41cae768c53d411dabcfea2333e2e138df22d909ed555ece426f1e016f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-fancy-pypi-readme
    - pip
  run:
    - typing_extensions >=4.10,<5
    - python >={{ python_min }}
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.7,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio

test:
  imports:
    - groq
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://console.groq.com/docs/quickstart
  summary: The official Python library for the groq API
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
